setwd("~/Dropbox/Muehlbauer_lab/Final_GAPIT_Results_from_MSI/Final_GWAS_Results_Compressed_with_Model_Selection/All_2015/")

#load results generated by the Compbine_All_SNPs_Sig_Traits_in_a_directory.R script

load("2015_All_Lines_50K_GBS_Merged_GWAS_Comp_with_Mod_Selection_All_SNPs.RData")

load("2015_All_Lines_50K_GBS_Merged_GWAS_Comp_with_Mod_Selection_Sig_SNPs.RData")

sig_traits <- as.factor(unique(as.character(sig_SNPs$Trait)))

Traits_Sig <- All_GWAS_Results[All_GWAS_Results$Trait %in% sig_traits,]
Traits_Sig$Cond <- "Compressed with Model Selection"

#required libraries
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(dplyr)
library(gridExtra)

Traits_Sig$Trait_Long <- paste(Traits_Sig$Trait,Traits_Sig$Year,Traits_Sig$Lines,Traits_Sig$Cond,sep="_")
Traits_Sig$Color <- "Not_Sig"
Traits_Sig[Traits_Sig$FDR_Adjusted_P.values<=0.01,][,"Color"] <- "Very_Sig"
Traits_Sig[Traits_Sig$FDR_Adjusted_P.values>0.01 & Traits_Sig$FDR_Adjusted_P.values<=0.05,][,"Color"] <- "Sig"

Traits_Sig$log10_pval <- -1*log10(Traits_Sig$P.value)

p <- ggplot(data=Traits_Sig, aes(x=Position/1000000, y=log10_pval, color=Color)) + 
  geom_point() + 
  facet_grid(. ~ Chromosome, scales="free", space="free") + 
  background_grid(major='y',minor="none") + 
  panel_border() + 
  scale_y_continuous(breaks=seq(0,100,by=2)) + 
  scale_x_continuous(breaks=seq(0,800,by=100)) + 
  labs(x="Position (Mb)",y="-log10(pval)") + 
  scale_color_manual(values=c("black","green3","red")) + 
  theme(axis.text.x=element_text(angle=90, vjust=0.5,size=9)) +
  theme(axis.text.y=element_text(size=9)) +
  theme(legend.position="None") + 
  theme(strip.background = element_blank()) + 
  theme(panel.spacing.x=unit(0.2,"lines")) + 
  theme(strip.text=element_text(size=10)) + 
  theme(axis.title.x = element_text(size=12)) + 
  theme(axis.title.y = element_text(size=12))

plots = Traits_Sig %>% 
  group_by(Trait_Long) %>%
  do(plots=p %+% .+ ggtitle(unique(.$Trait_Long)) )

p <- marrangeGrob(grobs=plots$plots, ncol=1, nrow=3)

tiff(file="All_Lines_2015_Comp_with_Model_Selection_50K_GBS_Merged_Man_Plot%02d.tif",units="in", width=7.5,height=10,res=600)
p
dev.off()

